---
- name: Install packages needed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Make dir for key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download the public signing key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
    state: present

- name: Add the appropriate Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
    state: present

- name: Update  packages
  ansible.builtin.apt:
    update_cache: true
    force: true

- name: Install kubelet, kubeadm and kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl

- name: Enable the kubelet service before running kubeadm
  ansible.builtin.service:
    name: kubelet
    enabled: true


# ------- Kube network
- name: Enable IPv4 packet forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
    reload: true

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: true

- name: Generate default containerd config
  ansible.builtin.command: sudo containerd config default
  register: containerd_config
  changed_when: containerd_config.rc != 0

- name: Create /etc/containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Write containerd config to /etc/containerd/config.toml
  ansible.builtin.copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'

- name: Update SystemdCgroup to true in containerd config
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*=\s*false'
    line: '            SystemdCgroup = true'
    insertafter: '\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\]'

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
# ----------------------- Auto-Complete

- name: Auto Complete kube
  ansible.builtin.apt:
    name: bash-completion
    state: present

- name: Add kubectl completion script to .bashrc
  ansible.builtin.lineinfile:
    path: /home/ubuntu/.bashrc
    line: 'source <(kubectl completion bash)'

- name: Apply changes to .bashrc
  ansible.builtin.shell: 'source /home/ubuntu/.bashrc'
  args:
    executable: /bin/bash
  register: my_output
  changed_when: my_output.rc != 0

# ----------------------- reload Daemon
- name: Reload Daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
