apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  namespace: devops
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: sonarqube-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-postgresql
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-postgresql
  template:
    metadata:
      labels:
        app: sonarqube-postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: sonarUser
        - name: POSTGRES_PASSWORD
          value: sonarPass
        - name: POSTGRES_DB
          value: sonarDB
