- name: Upgrade and update
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_requirment }}"

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable "
    state: present

- name: Install docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_packages }}"
  notify: upgrade and update

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add the users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ users }}"

# - name: open docker.sock to everyone
#   file:
#     path: /var/run/docker.sock
#     mode: 0760
